version: '3'

networks:
    app-tier:
        driver: bridge

services: 
    erlang.k8s.cluster-1:
        image: 'contactchanaka/erlang.k8s.cluster:0.0.1'
        build: .
        networks:
            - app-tier
        environment:
           - ERLANG_NODENAME='erlang_k8s@erlang.k8s.cluster-1'
           - CLUSTER_ERLANG_COOKIE='erlang.k8s.cluster'
           - K8S_HOSTNAME_SUFFIX=[]
           - WORLD_LIST=['erlang.k8s.cluster-1', 'erlang.k8s.cluster-2']

    erlang.k8s.cluster-2:
        image: 'contactchanaka/erlang.k8s.cluster:0.0.1'
        networks:
            - app-tier
        environment:
           - ERLANG_NODENAME='erlang_k8s@erlang.k8s.cluster-2'
           - CLUSTER_ERLANG_COOKIE='erlang.k8s.cluster'
           - K8S_HOSTNAME_SUFFIX=[]
           - WORLD_LIST=['erlang.k8s.cluster-1', 'erlang.k8s.cluster-2']